Repository pagopa/pagopa-api-config-fe, pull requests merged in 2022-06, with the labels that each got.

#85 Cosmetic fix
  src/pages/creditorInstitutions/CreditorInstitutions.tsx
Labels: bug

#86 [PCFG-223] PSP Section in Channel Page
  src/pages/channels/Channel.tsx
  src/pages/paymentServiceProviders/PaymentServiceProvider.tsx
Labels: enhancement

#90 [PCFG-238] fix payment type in Channel Page
  src/pages/channels/Channel.tsx
  src/pages/channels/EditChannel.tsx
Labels: bug

#91 [PCFG-242] Fix checkbox
  src/pages/channels/Channel.tsx
  src/pages/creditorInstitutions/CreditorInstitution.tsx
  src/pages/paymentServiceProviders/PaymentServiceProvider.tsx
Labels: bug

#92 [PCFG-245] Fix menu item
  src/components/Sidebar.tsx
Labels: ignore-for-release

#93 [PCFG-247] Input type check
  src/pages/channels/CreateChannel.tsx
  src/pages/channels/EditChannel.tsx
  src/pages/configuration/Pdds.tsx
  src/pages/creditorInstitutions/EditCreditorInstitution.tsx
  src/pages/icas/CheckICA.tsx
  src/pages/stations/CreateStation.tsx
  src/pages/stations/EditStation.tsx
Labels: bug

#94 [PCFG-239] Fix Protocol
  src/pages/brokers/CreateBrokerPage.tsx
  src/pages/brokers/EditBrokerPage.tsx
  src/pages/brokersPSP/CreateBrokerPSP.tsx
  src/pages/brokersPSP/EditBrokerPSP.tsx
  src/pages/channels/Channel.tsx
  src/pages/channels/CreateChannel.tsx
  src/pages/channels/EditChannel.tsx
  src/pages/creditorInstitutions/CreateCreditorInstitution.tsx
  src/pages/creditorInstitutions/EditCreditorInstitution.tsx
  src/pages/paymentServiceProviders/CreatePaymentServiceProvider.tsx
  src/pages/paymentServiceProviders/EditPaymentServiceProvider.tsx
  src/pages/stations/CreateStation.tsx
  src/pages/stations/EditStation.tsx
Labels: bug

#95 [PCFG-244] WFESP Plugin
  src/pages/channels/CreateChannel.tsx
  src/pages/channels/EditChannel.tsx
Labels: enhancement
