Repository pagopa/pagopa-api-config-fe, pull requests merged in 2023-02, with the labels that each got.

#129 PAGOPA-106 feat: adding clone station
  src/pages/channels/Channel.tsx
  src/pages/channels/CreateChannel.tsx
  src/pages/channels/EditChannel.tsx
  src/pages/stations/CreateStation.tsx
  src/pages/stations/EditStation.tsx
  src/pages/stations/Services.tsx
  src/pages/stations/Station.tsx
  src/pages/stations/StationView.tsx
  src/pages/stations/Stations.tsx
Labels: enhancement

#132 PAGOPA-635 code generalization for channels
  src/pages/channels/Channel.tsx
  src/pages/channels/ChannelView.tsx
  src/pages/channels/Channels.tsx
  src/pages/channels/CreateChannel.tsx
  src/pages/channels/EditChannel.tsx
  src/pages/channels/Services.tsx
Labels: enhancement

#135 PAGOPA-718 minor fix to primitive version
  src/pages/channels/ChannelView.tsx
Labels: bug

#136 [PAGOPA-708] fix: Associazione multipla EC-canali e Canali-Tipo versamento
  src/pages/channels/ChannelView.tsx
  src/pages/creditorInstitutions/EditCreditorInstitution.tsx
Labels: bug

#133 feat: Add refresh configurazione nodo PAGOPA-653
  src/__tests__/RefreshConfiguration.test.tsx
  src/components/SidebarItems.tsx
  src/pages/configuration/RefreshConfig.tsx
  src/util/routes.tsx
Labels: enhancement

#134 Version FE
  src/pages/Login.tsx
Labels: ignore-for-release
