Repository pagopa/pagopa-api-config-fe, pull requests merged in 2023-08, with the labels that each got.

#150 feat: remove refresh single instances PAGOPA-1052
  src/pages/configuration/RefreshConfig.tsx
Labels: enhancement

#151 [PAGOPA-1134] new GHA
  .devops/azure-templates/node-versioning.yml
  .devops/code-review-pipelines.yml
  .devops/deploy-pipelines.yml
  .github/workflows/code_review.yml
  .github/workflows/release_deploy.yml
  .identity/.terraform.lock.hcl
  .identity/00_data.tf
  .identity/02_application_action.tf
  .identity/03_github_environment.tf
  .identity/99_main.tf
  .identity/99_variables.tf
  .identity/env/dev/backend.ini
  .identity/env/dev/backend.tfvars
  .identity/env/dev/terraform.tfvars
  .identity/env/prod/backend.ini
  .identity/env/prod/backend.tfvars
  .identity/env/prod/terraform.tfvars
  .identity/env/uat/backend.ini
  .identity/env/uat/backend.tfvars
  .identity/env/uat/terraform.tfvars
  .identity/terraform.sh
  .sonar-project.properties
  package.json
  sonar-project.properties
Labels: ignore-for-release, size/large

#152 fix: pub date null for iban in EC page PAGOPA-1149
  src/pages/creditorInstitutions/CreditorInstitution.tsx
Labels: bug, size/small
